config/routes.rb
WeAsk::Application.routes.draw do

  put "votings/vote_up/:votable_type/:votable_id" => 'votings#vote_up', :as => :vote_up
  put "votings/vote_down/:votable_type/:votable_id" => 'votings#vote_down', :as => :vote_down

  resources :notifications

  resources :topics do
    resources :comments do
      member do
        put 'vote'
      end
    end
    member do
      put 'vote'
      put 'bookmark', :as => :bookmark
      put 'unbookmark', :as => :unbookmark
    end
  end

  devise_for :users

  put 'users/update_avatar' => 'users#update_avatar', :as => :update_avatar
  put 'users/update_account' => 'users#update_account', :as => :update_account

  resources :users do
    member do
      put 'follow'
      put 'unfollow'
      put 'remove_follower'
      get 'notifications/(:unread)' => 'users#notifications', :as => :notifications
    end
  end
  namespace :admin do
    resources :users do
      member do
        put 'toggle_blocked'
      end
    end
    resources :nodes
    resources :topics
    resources :comments
  end

  root :to => "topics#index"
  
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  attr_accessible :block_comments, :comments_count, :content, :last_replied_by, :node_id, :title, :creator_id

  belongs_to :node
  belongs_to :creator, class_name: 'User'

  validates_presence_of :node_id, :creator_id

  has_many :comments, as: :commentable
  has_many :votings, as: :votable

  has_many :bookmarks, as: :bookmarkable, dependent: :destroy
  has_many :interested_users, through: :bookmarks, source: :user

  RANKING_GRAVITY = 1.8


  def comments_count
    comments.size
  end

  def votings_up_count
    votings.select { |v| v.is_up }.size
  end

  def votings_down_count
    - votings.select { |v| !v.is_up }.size
  end

  def voted_by?(user)
    votings.any? { |v| v.creator == user }
  end

  def last_replied_by
    comments.last.creator.nickname if comments_count > 1
  end

  def linking
    "<a href='/topics/#{self.id}'>#{self.title}</a>"
  end

  def bookmarked_by?(user)
    interested_users.include?(user)
  end

  def ranking
    x = votings_up_count + votings_down_count
    y = x == 0 ? 0 : ( x > 0 ? 1 : -1 )
    z = x == 0 ? 1 : x.abs
    t = created_at - Time.new( 1970, 1, 1 )

    Math.log10(z) + ( y*t / 45000 )

  end

end

app/controllers/admin/topics_controller.rb
class Admin::TopicsController < ApplicationController
  layout "admin"
  def index
    @topics = Topic.all
  end

  def edit
    @topic = Topic.find(params[:id])
  end

  def show
    @topic = Topic.find(params[:id])
  end

  def update
    @topic = Topic.find(params[:id])
    respond_to do |format|
      if @topic.update_attributes(params[:topic])
        format.html { redirect_to [:admin, @topic], notice: 'topic updated successfully' }
      else
        format.html { render :edit , error: 'topic updated failed' }
      end    
    end    
  end

  def destroy
    @topic = Topic.find(params[:id])
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to admin_topics_url }
    end
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

  before_filter :authenticate_user!, :except => [:index, :show]


  # GET /topics
  # GET /topics.json
  def index
    @topics = Topic.all.sort_by(&:ranking).reverse

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @topics }
    end
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
    @topic = Topic.find(params[:id])
    @comment = Comment.new({ commentable_type: Topic.to_s, commentable_id: @topic.id })

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @topic }
    end
  end

  # GET /topics/new
  # GET /topics/new.json
  def new
    @topic = Topic.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @topic }
    end
  end

  # GET /topics/1/edit
  def edit
    @topic = Topic.find(params[:id])
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(params[:topic])
    @topic.creator = current_user

    respond_to do |format|
      if @topic.save
        format.html { redirect_to @topic, notice: 'Topic was successfully created.' }
        format.json { render json: @topic, status: :created, location: @topic }
      else
        format.html { render action: "new" }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /topics/1
  # PUT /topics/1.json
  def update
    @topic = Topic.find(params[:id])

    respond_to do |format|
      if @topic.update_attributes(params[:topic])
        format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic = Topic.find(params[:id])
    @topic.destroy

    respond_to do |format|
      format.html { redirect_to topics_url }
      format.json { head :no_content }
    end
  end

  def bookmark
    @topic = Topic.find(params[:id])
    unless @topic.bookmarked_by?(current_user)
      bm = @topic.bookmarks.build
      bm.user = current_user
      bm.save
    end
    respond_to do |format|
      format.html { redirect_to @topic }
    end
  end

  def unbookmark
    @topic = Topic.find(params[:id])
    if @topic.bookmarked_by?(current_user)
      bm = Bookmark.where({ 
        user_id: current_user, bookmarkable_id: @topic })
      @topic.bookmarks.destroy(bm)
    end
    respond_to do |format|
      format.html { redirect_to @topic }
    end
  end

end

app/helpers/admin/topics_helper.rb
module Admin::TopicsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.haml
= simple_form_for(@topic, :html => { :class => 'form-horizontal' }) do |f|
  = f.error_notification

  .form-inputs
    = f.association :node, collection: Node.all, required:true
    = f.input :title
    = f.input :content
    
    = f.input :block_comments

  .form-actions
    = f.button :submit, :class => 'btn btn-primary'

app/views/topics/edit.html.haml
%h1 Editing topic

= render 'form'

= link_to 'Show', @topic
\|
= link_to 'Back', topics_path

app/views/topics/index.html.haml
%h3 Topics

.topics-list
  - @topics.each do |topic|
    .topic.clearfix
      .topic-creator.pull-left
        = medium_avatar topic.creator
        = topic.creator.nickname
      .topic-brief.pull-left
        .topic-title
          = link_to topic.title, topic_path(topic)
        .topic-content
          = topic.content
        .topic-comment
          #{topic.comments_count} 条回复,最后回复：#{topic.last_replied_by}
      .topic-votings.pull-right
        .topic-voted-up
          = topic.votings_up_count
        .topic-voted-down
          = topic.votings_down_count

= content_for :sidebar do
  - if user_signed_in?
    .bookmarks-count
      #{current_user.bookmarks_count} 个收藏
    = link_to 'New Topic', new_topic_path, :class => 'btn btn-primary'

app/views/topics/new.html.haml
%h1 New topic

= render 'form'

= link_to 'Back', topics_path

app/views/topics/show.html.haml
%p#notice= notice

.topic-wrapper
  = render partial: 'votings/votings', locals: { votable: @topic }
  %h3
    = @topic.title
  .topic-meta
    作者：
    = @topic.creator.nickname
    发布日期：
    = @topic.updated_at
    最后回复：
    = @topic.last_replied_by
  .topic-content
    = @topic.content
  .topic-like
    - if user_signed_in?
      - unless @topic.bookmarked_by?(current_user)
        = link_to '收藏', bookmark_topic_path(@topic), method: :put
      - else
        = link_to '取消收藏', unbookmark_topic_path(@topic), method: :put
- if @topic.block_comments?
  %h6
    本贴禁止了回复功能
-else
  %h3
    评论
  .topic-comments-wrapper
    - @topic.comments.each_with_index do |comment, index|
      .comment-wrapper
        = render partial: 'votings/votings', locals: { votable: comment }
        .comment-creator
          %span.floor
            #{index+1}楼
          ,
          %span.name
            #{ comment.creator.nickname } 
          说: 
        .comment-content
          = comment.html_content.html_safe
        .reply-comment
          =link_to '回复', '', :onclick => 'return false;'
  = render partial: 'comments/form', locals: { commentable: @topic } 

= content_for :sidebar do
  - if user_signed_in?
    .bookmarks-count
      #{current_user.bookmarks_count} 个收藏
    = link_to 'New Topic', new_topic_path, :class => 'btn btn-primary'