config/routes.rb
WeAsk::Application.routes.draw do

  put "votings/vote_up/:votable_type/:votable_id" => 'votings#vote_up', :as => :vote_up
  put "votings/vote_down/:votable_type/:votable_id" => 'votings#vote_down', :as => :vote_down

  resources :notifications

  resources :topics do
    resources :comments do
      member do
        put 'vote'
      end
    end
    member do
      put 'vote'
      put 'bookmark', :as => :bookmark
      put 'unbookmark', :as => :unbookmark
    end
  end

  devise_for :users

  put 'users/update_avatar' => 'users#update_avatar', :as => :update_avatar
  put 'users/update_account' => 'users#update_account', :as => :update_account

  resources :users do
    member do
      put 'follow'
      put 'unfollow'
      put 'remove_follower'
      get 'notifications/(:unread)' => 'users#notifications', :as => :notifications
    end
  end
  namespace :admin do
    resources :users do
      member do
        put 'toggle_blocked'
      end
    end
    resources :nodes
    resources :topics
    resources :comments
  end

  root :to => "topics#index"
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :avatar, :blocked, :email, :nickname, :reward, :role
  attr_accessible :account_attributes
  attr_accessible :followers, :followings


  mount_uploader :avatar, AvatarUploader

  has_one :account, :dependent => :destroy
  accepts_nested_attributes_for :account
  before_create :create_account

  has_many :topics, :foreign_key => 'creator_id', dependent: :destroy

  has_many :bookmarks, dependent: :destroy

  has_many :follower_relationships, class_name: 'Follow', foreign_key: :following_id, dependent: :destroy
  has_many :followers, through: :follower_relationships

  has_many :following_relationships, class_name: 'Follow', foreign_key: :follower_id, dependent: :destroy
  has_many :followings, through: :following_relationships


  def admin?
    nickname == 'aaaaa'
  end

  # user had already voted the votable object?
  def voted?(votable)
    votable.voted_by?(self)
  end

  def following?(user)
    followings.include?(user)
  end

  def followed_by?(user)
    followers.include?(user)
  end

  def follow(user)
    following_relationships.create(following_id: user.id) if !following?(user) and self != user
  end

  def unfollow(user)
    followings.delete(user) if following?(user)
  end

  def unread_notifications_count
    Notification.where(user_id: self.id, unread: true).count
  end
  def notifications(unread)
    Notification.where(user_id: self.id, unread: unread)
  end

  def remove_follower(user)
    followers.delete(user) if followed_by?(user)
  end

  def bookmarks_count
    bookmarks.count
  end

  def bookmark_topics
    bookmarks.select { |bm| bm.bookmarkable_tyep == 'Topic' }
  end



private 
  def create_account
    self.build_account if self.account.nil?
  end
    
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  layout "admin"
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def toggle_blocked
    @user = User.find(params[:id])
    @user.update_attributes({ blocked: !@user.blocked})
    respond_to do |format|
      format.js
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      respond_to do |format|
        format.html { redirect_to admin_users_url }
      end
    else
      respond_to do |format|
        format.html { redirect_to edit_admin_user_url(@user) }
      end
    end

  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    respond_to do |format|
      format.html { redirect_to admin_users_url }
    end
  end
end

app/controllers/users_controller.rb
# encoding: utf-8

class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    Mailer.test_email(@user).deliver
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
    authorize! :edit, @user
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])
    
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = current_user

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update_avatar
    @user = current_user
    respond_to do |format|
      if @user.update_without_password(params[:user])
        format.html { redirect_to @user, notice: '成功更新头像.' }
      else
        format.html { render :edit }
      end
    end
  end

  def update_account
    @user = current_user
    respond_to do |format|
      if @user.update_without_password(params[:user])
        format.html { redirect_to @user, notice: '成功更新个人信息.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  def follow
    @user = User.find(params[:id])
    current_user.follow(@user)
    respond_to do |format|
      format.html { redirect_to @user }
      format.json { head :no_content }
    end
  end

  def unfollow
    @user = User.find(params[:id])
    current_user.unfollow(@user)
    respond_to do |format|
      format.html { redirect_to @user }
      format.json { head :no_content }
      format.js {  }
    end
  end

  def remove_follower
    @user = User.find(params[:id])
    current_user.remove_follower(@user)
    respond_to do |format|
      format.html { redirect_to current_user }
      format.json { head :no_content }
    end
  end

  def notifications
    @unread = params[:unread] == '1'
    @user = User.find(params[:id])
    @notifications = @user.notifications @unread
    respond_to do |format|
      format.html {
        Notification.where(id: @notifications.collect(&:id)).update_all(:unread => false)
      }
    end
  end

  def add_bookmark
    @user = User.find(params[:id])
    bookmark = @user.bookmarks.build(bookmarkable_id: params[:bookmarkable_id])
    @saved = bookmark.save
    respond_to do |format|
      format.js { }
    end

  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_account_form.html.haml
= f.fields_for :account do |fields|
  = fields.input :real_name
  = fields.input :school, :required => true
  = fields.input :address

app/views/users/_avatar_form.html.haml
%fieldset
  %legend
    现在的头像
  .span
    = large_avatar @user
    大头像
  .span
    = medium_avatar @user
    中头像
  .span
    = thumb_avatar @user
    小头像

%fieldset
  %legend
    上传新头像
  
  = simple_form_for @user, :url => update_avatar_path, :html => { :multipart => true, :class => 'edit-avatar form-horizontal' } do |f|
    = f.input :avatar, :label => ''

    .form-actions
      = f.submit '更新头像', :class => 'btn btn-primary'

app/views/users/_followers.html.haml
- if !user.followers.blank?
  %h4
    my followers
  %table
    %thead
      %tr
        %td
        %td
    %tbody
      - user.followers.each do |follower|
        %tr
          %td 
            = follower.nickname
          %td
            = link_to 'remove', remove_follower_user_path(user), method: :put, :class => 'btn btn-primary'

app/views/users/_followings.html.haml
- if !user.followings.blank?
  %h4
    my followings
  %table
    %thead
      %tr
        %td
        %td
    %tbody
      - user.followings.each do |following|
        %tr{ :id => "following_#{following.id.to_s }" }
          %td 
            = following.nickname
          %td
            = link_to 'unfollow', unfollow_user_path(following, :target => "following_#{following.id.to_s }" ), 
                method: :put, :class => 'btn btn-primary', :remote => true

app/views/users/_form.html.haml
= simple_form_for @user, :url => update_account_path, :html => { :class => 'edit-user form-horizontal' } do |f|
  = f.input :nickname
  = render :partial => 'account_form', :locals => {:f => f}

  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), users_path, :class => 'btn'

app/views/users/add_bookmark.js.haml
- if @saved
  $('.topic-like').replaceWith('已收藏')

app/views/users/edit.html.haml
- model_class = User
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human
= render :partial => 'form'

= render :partial => 'avatar_form'

app/views/users/index.html.haml
- model_class = User
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:avatar)
      %th= model_class.human_attribute_name(:nickname)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @users.each do |user|
      - next if user == current_user
      %tr
        %td= thumb_avatar user
        %td
          = link_to user.nickname, user_path(user)
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_user_path(user), :class => 'btn btn-mini btn-primary'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), user_path(user), :method => :delete, 
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_user_path, :class => 'btn btn-primary'

app/views/users/new.html.haml
- model_class = User
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human

= simple_form_for @user, :html => { :multipart => true, :class => 'edit-user form-horizontal' } do |f|
  = f.input :nickname
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), users_path, :class => 'btn'

app/views/users/notifications.html.haml
.page-header
  %h4 #{ @unread ? '未读通知' : '已读通知' }
%table.table.table-striped
  %tbody
    - @notifications.each do |nf|
      %tr
        %td= nf.notification_title.html_safe
      %tr
        %td= nf.notification_message.html_safe
      %tr
        %td

app/views/users/show.html.haml
- model_class = User
.page-header
  %h1=t '.title', :default => model_class.model_name.human

%p
  %strong= model_class.human_attribute_name(:nickname) + ':'
  %br
  = @user.nickname
%p
  %strong= model_class.human_attribute_name(:avatar) + ':'
  %br
  = medium_avatar @user
%p
  %strong= model_class.human_attribute_name(:email) + ':'
  %br
  = @user.email


- if current_user == @user
  = render partial: 'followers', locals: { user: @user }
  = render partial: 'followings', locals: { user: @user }
- elsif user_signed_in?
  .form-actions
    - if current_user.following?(@user)
      = link_to 'unfollow', unfollow_user_path(@user), method: :put, :class => 'btn btn-primary'
    - elsif current_user != @user
      = link_to 'follow', follow_user_path(@user), method: :put, :class => 'btn btn-primary'

app/views/users/unfollow.js.haml
$('##{params[:target]}').remove();