config/routes.rb
WeAsk::Application.routes.draw do

  put "votings/vote_up/:votable_type/:votable_id" => 'votings#vote_up', :as => :vote_up
  put "votings/vote_down/:votable_type/:votable_id" => 'votings#vote_down', :as => :vote_down

  resources :notifications

  resources :topics do
    resources :comments do
      member do
        put 'vote'
      end
    end
    member do
      put 'vote'
      put 'bookmark', :as => :bookmark
      put 'unbookmark', :as => :unbookmark
    end
  end

  devise_for :users

  put 'users/update_avatar' => 'users#update_avatar', :as => :update_avatar
  put 'users/update_account' => 'users#update_account', :as => :update_account

  resources :users do
    member do
      put 'follow'
      put 'unfollow'
      put 'remove_follower'
      get 'notifications/(:unread)' => 'users#notifications', :as => :notifications
    end
  end
  namespace :admin do
    resources :users do
      member do
        put 'toggle_blocked'
      end
    end
    resources :nodes
    resources :topics
    resources :comments
  end

  root :to => "topics#index"
  
end

app/views/layouts/admin.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "WeAsk"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    %link(href="images/apple-touch-icon-144x144.png" rel="apple-touch-icon-precomposed" sizes="144x144")
    %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon-precomposed" sizes="114x114")
    %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon-precomposed" sizes="72x72")
    %link(href="images/apple-touch-icon.png" rel="apple-touch-icon-precomposed")
    %link(href="favicon.ico" rel="shortcut icon")


  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand(href="#") WeAsk
          .container.nav-collapse
            %ul.nav
              %li= link_to "首页", topics_url
              %li= link_to "用户", users_url
            %ul.nav.pull-right
              - if user_signed_in?
                %li= link_to "登陆为 #{current_user.nickname}", user_path(current_user)
                %li= link_to "设置", edit_user_path(current_user)
                %li= link_to "退出", destroy_user_session_path, :method => :delete
              - else
                %li= link_to "登陆", new_user_session_path
                %li= link_to "注册", new_user_registration_path

    .container
      = bootstrap_flash
      .row
        .span2
          %ul.nav.admin-sidebar.nav-list
            = render_admin_sidebar
        .span8
          .admin-content
            = yield
        .span2
      %footer

    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "WeAsk"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = javascript_include_tag "application"
    = stylesheet_link_tag "application", :media => "all"
    %link(href="images/apple-touch-icon-144x144.png" rel="apple-touch-icon-precomposed" sizes="144x144")
    %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon-precomposed" sizes="114x114")
    %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon-precomposed" sizes="72x72")
    %link(href="images/apple-touch-icon.png" rel="apple-touch-icon-precomposed")
    %link(href="/assets/favicon.ico" rel="shortcut icon")


  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand(href="#") WeAsk
          .container.nav-collapse
            %ul.nav
              %li= link_to "首页", topics_url
              %li= link_to "用户", users_url
            %ul.nav.pull-right
              - if user_signed_in?
                %li= link_to "登陆为 #{current_user.nickname}", user_path(current_user)
                %li= link_to "( #{current_user.unread_notifications_count} )", notifications_user_path(current_user, 1)
                %li= link_to "设置", edit_user_path(current_user)
                %li= link_to "系统设置", admin_users_path if current_user.admin?
                %li= link_to "退出", destroy_user_session_path, :method => :delete
              - else
                %li= link_to "登陆", new_user_session_path
                %li= link_to "注册", new_user_registration_path

    .container
      .row
        .span9
          = bootstrap_flash
          = yield
        .span3
          - if content_for? :sidebar
            .well.sidebar-nav
              %h3 Sidebar
              = yield :sidebar

            / %ul.nav.nav-list
            /   %li.nav-header Sidebar
            /   %li= link_to "Link 1", "/path1"
            /   %li= link_to "Link 2", "/path2"
            /   %li= link_to "Link 3", "/path3"
    
      %footer

    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    - if content_for? :footer
      = yield :footer